version: '3'

services:
  etcd:
    image: "quay.io/coreos/etcd:v3.3"
    container_name: "etcdv3.3"
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    volumes: 
      - ./default.etcd:/default.etcd
    ports:
    - 2379:2379
    - 2380:2380
    - 4001:4001
  etcd-manage:
    build: .
    # image: "shiguanghuxian/etcd-manage"
    volumes:
      - ./bin/config/cfg.toml:/app/config/cfg.toml
      - ./bin/logs:/app/logs
    ports:
      - "10280:10280"
    depends_on:
      - etcd
